name: Test SPT

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: false
        default: 'twrp-12.1'
        type: choice
        options:
        - twrp-12.1
        - twrp-11
        - twrp-9.0
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: false
        default: 'https://github.com/brigudav/android_device_xiaomi_surya_twrp'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: false
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: false
        default: 'device/xiaomi/surya'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: false
        default: 'surya'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: false
        default: 'recovery'
        type: choice
        options:
        - recovery
        - boot
        - vendorboot
      APPLYPATCH:
        description: 'Apply diff.patch (true or false)'
        required: false
        default: 'yes'
        type: choice
        options:
        - yes
        - no
      UPLOAD:
        description: 'Upload to Telegram Bot (true or false)'
        required: false
        default: 'yes'
        type: choice
        options:
        - yes
        - no
      PUBLISH:
        description: 'Publish to GitHub (true or false)'
        required: false
        default: 'yes'
        type: choice
        options:
        - yes
        - no

jobs:
  build:
    name: TEST SPT  by ${{ github.actor }}
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev \
          x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev \
          lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool \
          squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Python 2
      if: github.event.inputs.MANIFEST_BRANCH != 'twrp-11' && github.event.inputs.MANIFEST_BRANCH != 'twrp-12.1'
      run: |
        sudo apt -y install python2
        cd /usr/bin
        sudo ln -sf python2 python

    - name: Switch to Python3
      if: github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1'
      run: |
        sudo rm -rf /usr/bin/python
        sudo ln -s /usr/bin/python3 /usr/bin/python
      continue-on-error: true

    - name: Check Manifest Branch
      uses: haya14busa/action-cond@v1
      id: manifest
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1' }}
        if_true: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
        if_false: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: Initialize repo
      run: |
        mkdir twrp
        cd twrp
        echo "wsdir=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "brigudav"
        git config --global user.email "alexvl1972@hotmail.com"
        repo init --depth=1 -u ${{ steps.manifest.outputs.value }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd
      
    - name: Install Speedtest
      run: |
        sudo apt-get install curl
        curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
        sudo apt-get install speedtest
        
    - name: Run Speedtest
      run: |
        speedtest
